import { LegalLayout } from '@/components/landing/LegalLayout'

export const metadata = {
  title: 'Terms of Service — VeriGhana',
  description: 'Terms and conditions for using the VeriGhana fact-checking platform.',
}

export default function TermsPage() {
  return (
    <LegalLayout
      title="Terms of Service"
      subtitle="Please read these terms carefully before using VeriGhana."
      lastUpdated="March 2026"
      sections={[
        {
          heading: '1. Acceptance of Terms',
          body: (
            <p>
              By creating an account or using VeriGhana, you agree to be bound by these Terms of Service.
              If you do not agree, please do not use the platform. These terms apply to all users including
              free, Pro, and Institutional subscribers.
            </p>
          ),
        },
        {
          heading: '2. Description of Service',
          body: (
            <p>
              VeriGhana provides AI-assisted fact-checking for claims related to Ghana. We index articles
              from trusted Ghanaian news sources and use multiple AI models to assess the veracity of
              submitted claims. Verdicts are provided for informational purposes and do not constitute
              legal, journalistic, or professional advice.
            </p>
          ),
        },
        {
          heading: '3. Accuracy Disclaimer',
          body: (
            <>
              <p>
                VeriGhana uses AI models and automated web scraping. While we strive for accuracy, we
                cannot guarantee that every verdict is correct. Factors that may affect accuracy include:
              </p>
              <ul className="list-disc pl-5 space-y-1 mt-2">
                <li>Incomplete or outdated source articles in our index</li>
                <li>Limitations of current AI language models</li>
                <li>Rapidly evolving news situations</li>
              </ul>
              <p className="mt-3">
                Always cross-reference important claims with primary sources. VeriGhana verdicts should
                not be the sole basis for editorial, legal, or policy decisions.
              </p>
            </>
          ),
        },
        {
          heading: '4. Acceptable Use',
          body: (
            <>
              <p>You agree not to use VeriGhana to:</p>
              <ul className="list-disc pl-5 space-y-1 mt-2">
                <li>Submit claims containing personal data, hate speech, or illegal content</li>
                <li>Attempt to reverse-engineer, scrape, or abuse our API beyond your plan limits</li>
                <li>Misrepresent VeriGhana verdicts or use them in bad faith to harm individuals</li>
                <li>Create multiple free accounts to circumvent usage limits</li>
                <li>Use the platform for any unlawful purpose under Ghanaian or international law</li>
              </ul>
            </>
          ),
        },
        {
          heading: '5. Subscription Plans & Billing',
          body: (
            <>
              <p>
                VeriGhana offers three tiers: Free (5 verifications/day), Pro (₵0.99/month), and
                Institutional (₵1.99/month). Paid plans are billed in GHS monthly and processed by Paystack.
              </p>
              <ul className="list-disc pl-5 space-y-1 mt-2">
                <li>Subscriptions auto-renew unless cancelled before the billing date</li>
                <li>Refunds are available within 7 days of initial payment if no verifications have been made on the paid tier</li>
                <li>We reserve the right to change pricing with 30 days' notice to existing subscribers</li>
              </ul>
            </>
          ),
        },
        {
          heading: '6. Intellectual Property',
          body: (
            <p>
              The VeriGhana platform, including its design, code, and AI pipeline, is the intellectual
              property of the VeriGhana research team. News articles indexed from third-party sources
              remain the property of their respective publishers. Verdicts and explanations generated by
              VeriGhana may be shared with attribution to VeriGhana.
            </p>
          ),
        },
        {
          heading: '7. Account Termination',
          body: (
            <p>
              We reserve the right to suspend or terminate accounts that violate these terms, engage in
              abuse, or are used for fraudulent activity. You may delete your account at any time from
              your account settings. Upon deletion, your personal data will be removed within 30 days,
              except where retention is required by law.
            </p>
          ),
        },
        {
          heading: '8. Limitation of Liability',
          body: (
            <p>
              To the fullest extent permitted by law, VeriGhana and its developers shall not be liable
              for any indirect, incidental, or consequential damages arising from your use of the platform,
              including reliance on any verdict provided. Our total liability for any claim shall not
              exceed the amount you paid in the 3 months prior to the event giving rise to the claim.
            </p>
          ),
        },
        {
          heading: '9. Governing Law',
          body: (
            <p>
              These terms are governed by the laws of the Republic of Ghana. Any disputes shall be
              resolved in the courts of Ghana. If any provision of these terms is found unenforceable,
              the remaining provisions continue in full effect.
            </p>
          ),
        },
        {
          heading: '10. Contact',
          body: (
            <p>
              For questions about these terms, email <strong>legal@verighana.com</strong> or use the{' '}
              <a href="/app/contact" className="text-blue-600 hover:underline">contact form</a> in your dashboard.
            </p>
          ),
        },
      ]}
    />
  )
}
